name: CI
on: 
  push: 
    branches: 
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v2

      - name: Setup Node 
        uses: actions/setup-node@v2

      - name: Release 
        run: npm run release 



